<#
.SYNOPSIS
  Regenerates desktop/runtime — the self-contained DSH runtime that the desktop
  build ships inside resources/runtime.

.DESCRIPTION
  Produces:

    runtime/node/node.exe        a stock Node.js binary
    runtime/app/node_modules/    a production-only install of @deepseek-ai/dsh

  Electron is only the shell; DSH itself runs on this bundled node.exe. Shipping
  the interpreter instead of borrowing the host's means the packaged app behaves
  identically on machines that have no Node.js at all, and it sidesteps the
  Electron/Node ABI mismatch entirely (Electron's own node cannot load the
  native node-pty / sharp prebuilds used by the terminal and attachment
  plugins).

  `--ignore-scripts` is deliberate. @deepseek-ai/dsh pulls native dependencies
  whose prebuilt binaries ship inside their npm tarballs, so no compilation or
  postinstall step is required — and skipping scripts keeps the install working
  in shells that refuse to spawn build tooling.

.PARAMETER DshVersion
  Exact @deepseek-ai/dsh version to bundle. Must be a concrete version, not a
  range, so rebuilds are reproducible.

.PARAMETER NodeExe
  Node.js binary to embed. Defaults to the `node` on PATH.

.PARAMETER NpmCache
  Optional npm cache directory. Leave unset to use npm's default.

.EXAMPLE
  npm run prepare:runtime
  ./scripts/prepare-runtime.ps1 -DshVersion 0.1.5-rc.2
#>

[CmdletBinding()]
param(
    [string]$DshVersion = '0.1.5-rc.2',
    [string]$NodeExe,
    [string]$NpmCache
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$projectRoot = Split-Path -Parent $PSScriptRoot
$runtimeDir  = Join-Path $projectRoot 'runtime'
$nodeDir     = Join-Path $runtimeDir 'node'
$appDir      = Join-Path $runtimeDir 'app'
$logoSource  = Join-Path $projectRoot 'electron\logo.svg'

if (-not $NodeExe) {
    $NodeExe = (Get-Command node -ErrorAction Stop).Source
}
if (-not (Test-Path $NodeExe)) {
    throw "node.exe not found at '$NodeExe'. Pass -NodeExe explicitly."
}

Write-Host "runtime  : $runtimeDir"
Write-Host -NoNewline "node     : $NodeExe  ("
& $NodeExe -v
Write-Host ")"
Write-Host "dsh      : $DshVersion"

# ── 1. clean ────────────────────────────────────────────────────────────────

foreach ($stale in @($nodeDir, (Join-Path $appDir 'node_modules'))) {
    if (Test-Path $stale) {
        Write-Host "cleaning : $stale"
        Remove-Item $stale -Recurse -Force
    }
}
New-Item -ItemType Directory -Force -Path $nodeDir, $appDir | Out-Null

# ── 2. interpreter ──────────────────────────────────────────────────────────

Copy-Item $NodeExe -Destination (Join-Path $nodeDir 'node.exe') -Force

# The updater installs new DSH versions at runtime by invoking npm, so npm ships
# alongside the interpreter. Delegating to npm instead of reimplementing
# registry access means updates inherit whatever registry, proxy and TLS
# configuration already works on the user's machine.
$npmSource = Join-Path (Split-Path -Parent $NodeExe) 'node_modules\npm'
if (-not (Test-Path (Join-Path $npmSource 'bin\npm-cli.js'))) {
    throw "npm not found next to node at '$npmSource'. Install npm alongside node, or vendor it manually."
}
Copy-Item $npmSource -Destination (Join-Path $nodeDir 'node_modules\npm') -Recurse -Force

# ── 3. runtime packages ─────────────────────────────────────────────────────

$manifest = [ordered]@{
    name         = 'dsh-desktop-runtime'
    private      = $true
    version      = $DshVersion
    description  = 'Bundled DeepSeek Harness runtime for the desktop build. Regenerated by scripts/prepare-runtime.ps1.'
    license      = 'MIT'
    dependencies = [ordered]@{ '@deepseek-ai/dsh' = $DshVersion }
}
$manifest | ConvertTo-Json -Depth 5 |
    Set-Content -Path (Join-Path $appDir 'package.json') -Encoding utf8

$npmCli = Join-Path (Split-Path -Parent $NodeExe) 'node_modules\npm\bin\npm-cli.js'
if (-not (Test-Path $npmCli)) {
    throw "npm CLI not found at '$npmCli'; install npm alongside node or run the install manually."
}

if ($NpmCache) {
    $env:npm_config_cache = $NpmCache
}

Push-Location $appDir
try {
    & $NodeExe $npmCli install --omit=dev --ignore-scripts --no-audit --no-fund --loglevel=warn
    if ($LASTEXITCODE -ne 0) { throw "npm install failed with exit code $LASTEXITCODE" }
}
finally {
    Pop-Location
}

# ── 4. verify the pieces the shell depends on ───────────────────────────────

$closedChecks = [ordered]@{
    'dsh entry point' = 'node_modules\@deepseek-ai\dsh\lib\bin.js'
    'node-pty'        = 'node_modules\node-pty\prebuilds\win32-x64\conpty.node'
    'ripgrep'         = 'node_modules\@vscode\ripgrep-win32-x64\bin\rg.exe'
    'web frontend'    = 'node_modules\@deepseek-ai\dsh-web-frontend\dist\index.html'
    'brand asset'     = 'node_modules\@deepseek-ai\dsh-web-frontend\dist\favicon.svg'
}

$missing = @()
foreach ($entry in $closedChecks.GetEnumerator()) {
    $path = Join-Path $appDir $entry.Value
    $ok = Test-Path $path
    if (-not $ok) { $missing += $entry.Key }
    '{0,-16} {1}' -f $entry.Key, $(if ($ok) { 'ok' } else { "MISSING ($($entry.Value))" }) | Write-Host
}

# sharp names its platform binary after its own version, so match the directory.
$sharpLib = Join-Path $appDir 'node_modules\@img\sharp-win32-x64\lib'
$sharpOk = (Test-Path $sharpLib) -and
    @(Get-ChildItem $sharpLib -Filter '*.node' -ErrorAction SilentlyContinue).Count -gt 0
if (-not $sharpOk) { $missing += 'sharp' }
'{0,-16} {1}' -f 'sharp', $(if ($sharpOk) { 'ok' } else { 'MISSING' }) | Write-Host

# The shell's updater shells out to this entry point at runtime.
$bundledNpmCli = Join-Path $nodeDir 'node_modules\npm\bin\npm-cli.js'
$npmOk = Test-Path $bundledNpmCli
if (-not $npmOk) { $missing += 'bundled npm (updater)' }
'{0,-16} {1}' -f 'bundled npm', $(if ($npmOk) { 'ok' } else { 'MISSING' }) | Write-Host

if ($missing.Count -gt 0) {
    throw "runtime is incomplete; missing: $($missing -join ', ')"
}

# ── 5. refresh the shell's copy of the official brand mark ──────────────────

Copy-Item (Join-Path $appDir 'node_modules\@deepseek-ai\dsh-web-frontend\dist\favicon.svg') `
    -Destination $logoSource -Force

# ── 6. report ───────────────────────────────────────────────────────────────

$nodeMb = [math]::Round((Get-Item (Join-Path $nodeDir 'node.exe')).Length / 1MB, 1)
$npmMb = [math]::Round((Get-ChildItem (Join-Path $nodeDir 'node_modules\npm') -Recurse -File |
        Measure-Object Length -Sum).Sum / 1MB, 1)
$appMb  = [math]::Round((Get-ChildItem $appDir -Recurse -File |
        Measure-Object Length -Sum).Sum / 1MB, 1)
$packages = (Get-ChildItem (Join-Path $appDir 'node_modules') -Directory |
        Where-Object { $_.Name -notlike '@*' }).Count

Write-Host ''
Write-Host "node.exe  : $nodeMb MB"
Write-Host "npm       : $npmMb MB (used by the in-app updater)"
Write-Host "runtime   : $appMb MB across $packages top-level packages"
Write-Host "logo      : refreshed from the bundled favicon"
Write-Host ''
Write-Host 'Next: npm run make:icon ; npm run dist'
